//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfig) DeepCopyInto(out *PKIConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfig.
func (in *PKIConfig) DeepCopy() *PKIConfig {
	if in == nil {
		return nil
	}
	out := new(PKIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfigList) DeepCopyInto(out *PKIConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PKIConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfigList.
func (in *PKIConfigList) DeepCopy() *PKIConfigList {
	if in == nil {
		return nil
	}
	out := new(PKIConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfigObservation) DeepCopyInto(out *PKIConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfigObservation.
func (in *PKIConfigObservation) DeepCopy() *PKIConfigObservation {
	if in == nil {
		return nil
	}
	out := new(PKIConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfigParameters) DeepCopyInto(out *PKIConfigParameters) {
	*out = *in
	if in.KeyBits != nil {
		in, out := &in.KeyBits, &out.KeyBits
		*out = new(int)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ou != nil {
		in, out := &in.Ou, &out.Ou
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Province != nil {
		in, out := &in.Province, &out.Province
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddress != nil {
		in, out := &in.StreetAddress, &out.StreetAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PermittedDnsDomains != nil {
		in, out := &in.PermittedDnsDomains, &out.PermittedDnsDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxPathLength != nil {
		in, out := &in.MaxPathLength, &out.MaxPathLength
		*out = new(int)
		**out = **in
	}
	if in.ExcludeCnFromSans != nil {
		in, out := &in.ExcludeCnFromSans, &out.ExcludeCnFromSans
		*out = new(bool)
		**out = **in
	}
	if in.IssuingCertificates != nil {
		in, out := &in.IssuingCertificates, &out.IssuingCertificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CrlDistributionPoints != nil {
		in, out := &in.CrlDistributionPoints, &out.CrlDistributionPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OcspServers != nil {
		in, out := &in.OcspServers, &out.OcspServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CrlDisable != nil {
		in, out := &in.CrlDisable, &out.CrlDisable
		*out = new(bool)
		**out = **in
	}
	if in.OcspDisable != nil {
		in, out := &in.OcspDisable, &out.OcspDisable
		*out = new(bool)
		**out = **in
	}
	if in.CrlAutoRebuild != nil {
		in, out := &in.CrlAutoRebuild, &out.CrlAutoRebuild
		*out = new(bool)
		**out = **in
	}
	if in.CrlEnableDelta != nil {
		in, out := &in.CrlEnableDelta, &out.CrlEnableDelta
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfigParameters.
func (in *PKIConfigParameters) DeepCopy() *PKIConfigParameters {
	if in == nil {
		return nil
	}
	out := new(PKIConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfigSpec) DeepCopyInto(out *PKIConfigSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfigSpec.
func (in *PKIConfigSpec) DeepCopy() *PKIConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PKIConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfigStatus) DeepCopyInto(out *PKIConfigStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfigStatus.
func (in *PKIConfigStatus) DeepCopy() *PKIConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PKIConfigStatus)
	in.DeepCopyInto(out)
	return out
}
