//go:build !ignore_autogenerated

package v1beta1

import (
	xpv1 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

func (in *LDAPAuthConfig) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return in.Status.GetCondition(ct)
}

func (in *LDAPAuthConfig) SetConditions(c ...xpv1.Condition) {
	in.Status.SetConditions(c...)
}

func (in *LDAPAuthConfig) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return in.Spec.ProviderConfigReference
}

func (in *LDAPAuthConfig) GetManagementPolicies() xpv1.ManagementPolicies {
	return in.Spec.ManagementPolicies
}

func (in *LDAPAuthConfig) SetManagementPolicies(p xpv1.ManagementPolicies) {
	in.Spec.ManagementPolicies = p
}

func (in *LDAPAuthConfig) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return in.Spec.WriteConnectionSecretToReference
}

func (in *LDAPAuthConfig) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	in.Spec.WriteConnectionSecretToReference = r
}

func (in *LDAPAuthConfig) ConnectionSecretName() string {
	ref := in.GetWriteConnectionSecretToReference()
	if ref == nil {
		return ""
	}
	return ref.Name
}
