//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewal) DeepCopyInto(out *LeaseRenewal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewal.
func (in *LeaseRenewal) DeepCopy() *LeaseRenewal {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeaseRenewal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewalList) DeepCopyInto(out *LeaseRenewalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LeaseRenewal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewalList.
func (in *LeaseRenewalList) DeepCopy() *LeaseRenewalList {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeaseRenewalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewalObservation) DeepCopyInto(out *LeaseRenewalObservation) {
	*out = *in
	if in.LastRenewed != nil {
		in, out := &in.LastRenewed, &out.LastRenewed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewalObservation.
func (in *LeaseRenewalObservation) DeepCopy() *LeaseRenewalObservation {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewalObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewalParameters) DeepCopyInto(out *LeaseRenewalParameters) {
	*out = *in
	if in.Increment != nil {
		in, out := &in.Increment, &out.Increment
		*out = new(int)
		**out = **in
	}
	if in.RevokeOnDelete != nil {
		in, out := &in.RevokeOnDelete, &out.RevokeOnDelete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewalParameters.
func (in *LeaseRenewalParameters) DeepCopy() *LeaseRenewalParameters {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewalParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewalSpec) DeepCopyInto(out *LeaseRenewalSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewalSpec.
func (in *LeaseRenewalSpec) DeepCopy() *LeaseRenewalSpec {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseRenewalStatus) DeepCopyInto(out *LeaseRenewalStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseRenewalStatus.
func (in *LeaseRenewalStatus) DeepCopy() *LeaseRenewalStatus {
	if in == nil {
		return nil
	}
	out := new(LeaseRenewalStatus)
	in.DeepCopyInto(out)
	return out
}
