apiVersion: kvsecret.vault.m.crossplane.io/v1beta1
kind: KVSecret
metadata:
  name: myapp-credentials
spec:
  forProvider:
    mountPath: secret
    path: myapp/credentials
    data:
      username: admin
      password: s3cret
    version: 2
  providerConfigRef:
    name: vault-provider
  writeConnectionSecretToRef:
    name: myapp-credentials
    namespace: crossplane-system
