//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfig) DeepCopyInto(out *AzureAuthConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfig.
func (in *AzureAuthConfig) DeepCopy() *AzureAuthConfig {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureAuthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfigList) DeepCopyInto(out *AzureAuthConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureAuthConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfigList.
func (in *AzureAuthConfigList) DeepCopy() *AzureAuthConfigList {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureAuthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfigObservation) DeepCopyInto(out *AzureAuthConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfigObservation.
func (in *AzureAuthConfigObservation) DeepCopy() *AzureAuthConfigObservation {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfigParameters) DeepCopyInto(out *AzureAuthConfigParameters) {
	*out = *in
	if in.LoginMaxUserRetry != nil {
		in, out := &in.LoginMaxUserRetry, &out.LoginMaxUserRetry
		*out = new(int)
		**out = **in
	}
	if in.LoginScopes != nil {
		in, out := &in.LoginScopes, &out.LoginScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfigParameters.
func (in *AzureAuthConfigParameters) DeepCopy() *AzureAuthConfigParameters {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfigSpec) DeepCopyInto(out *AzureAuthConfigSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfigSpec.
func (in *AzureAuthConfigSpec) DeepCopy() *AzureAuthConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfigStatus) DeepCopyInto(out *AzureAuthConfigStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfigStatus.
func (in *AzureAuthConfigStatus) DeepCopy() *AzureAuthConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfigStatus)
	in.DeepCopyInto(out)
	return out
}
