//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKey) DeepCopyInto(out *TransitKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKey.
func (in *TransitKey) DeepCopy() *TransitKey {
	if in == nil {
		return nil
	}
	out := new(TransitKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransitKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKeyList) DeepCopyInto(out *TransitKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransitKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKeyList.
func (in *TransitKeyList) DeepCopy() *TransitKeyList {
	if in == nil {
		return nil
	}
	out := new(TransitKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransitKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKeyObservation) DeepCopyInto(out *TransitKeyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKeyObservation.
func (in *TransitKeyObservation) DeepCopy() *TransitKeyObservation {
	if in == nil {
		return nil
	}
	out := new(TransitKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKeyParameters) DeepCopyInto(out *TransitKeyParameters) {
	*out = *in
	if in.ConvergentEncryption != nil {
		in, out := &in.ConvergentEncryption, &out.ConvergentEncryption
		*out = new(bool)
		**out = **in
	}
	if in.Derived != nil {
		in, out := &in.Derived, &out.Derived
		*out = new(bool)
		**out = **in
	}
	if in.Exportable != nil {
		in, out := &in.Exportable, &out.Exportable
		*out = new(bool)
		**out = **in
	}
	if in.AllowPlaintextBackup != nil {
		in, out := &in.AllowPlaintextBackup, &out.AllowPlaintextBackup
		*out = new(bool)
		**out = **in
	}
	if in.MinDecryptionVersion != nil {
		in, out := &in.MinDecryptionVersion, &out.MinDecryptionVersion
		*out = new(int)
		**out = **in
	}
	if in.MinEncryptionVersion != nil {
		in, out := &in.MinEncryptionVersion, &out.MinEncryptionVersion
		*out = new(int)
		**out = **in
	}
	if in.RotateToVersion != nil {
		in, out := &in.RotateToVersion, &out.RotateToVersion
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKeyParameters.
func (in *TransitKeyParameters) DeepCopy() *TransitKeyParameters {
	if in == nil {
		return nil
	}
	out := new(TransitKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKeySpec) DeepCopyInto(out *TransitKeySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKeySpec.
func (in *TransitKeySpec) DeepCopy() *TransitKeySpec {
	if in == nil {
		return nil
	}
	out := new(TransitKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitKeyStatus) DeepCopyInto(out *TransitKeyStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitKeyStatus.
func (in *TransitKeyStatus) DeepCopy() *TransitKeyStatus {
	if in == nil {
		return nil
	}
	out := new(TransitKeyStatus)
	in.DeepCopyInto(out)
	return out
}
