//go:build !ignore_autogenerated

package v1beta1

import (
	xpv1 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

func (in *IdentityGroup) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return in.Status.GetCondition(ct)
}

func (in *IdentityGroup) SetConditions(c ...xpv1.Condition) {
	in.Status.SetConditions(c...)
}

func (in *IdentityGroup) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return in.Spec.ProviderConfigReference
}

func (in *IdentityGroup) GetManagementPolicies() xpv1.ManagementPolicies {
	return in.Spec.ManagementPolicies
}

func (in *IdentityGroup) SetManagementPolicies(p xpv1.ManagementPolicies) {
	in.Spec.ManagementPolicies = p
}

func (in *IdentityGroup) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return in.Spec.WriteConnectionSecretToReference
}

func (in *IdentityGroup) ConnectionSecretName() string {
	ref := in.GetWriteConnectionSecretToReference()
	if ref == nil {
		return ""
	}
	return ref.Name
}
