apiVersion: approlesecretid.vault.m.crossplane.io/v1beta1
kind: AppRoleSecretID
metadata:
  name: myapp-secretid
spec:
  forProvider:
    backend: approle
    role: myapp
    cidrList:
      - 10.0.0.0/8
  providerConfigRef:
    name: vault-provider
  writeConnectionSecretToRef:
    name: myapp-secretid
    namespace: crossplane-system
